name: Smoke Test and Security Scan

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  smoke-test:
    runs-on: ubuntu-latest
    services:
      redis:
        image: redis:latest
        ports:
          - 6379:6379
      docker:
        image: docker:latest
        options: --privileged

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest pytest-django pytest-cov

      - name: Run smoke tests
        run: |
          pytest backend/core/tests/test_smoke.py -v

      - name: Run security scan
        run: |
          # Install Trivy
          curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -s -- -b /usr/local/bin v0.18.3

          # Build sandbox image
          docker build -t kodewar-sandbox -f backend/sandbox/Dockerfile.sandbox .

          # Run Trivy scan
          trivy image kodewar-sandbox --severity HIGH,CRITICAL --exit-code 1

      - name: Run end-to-end tests
        run: |
          pytest backend/core/tests/test_integration.py -v

      - name: Upload test results
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: test-results
          path: |
            backend/core/tests/test_smoke.py
            backend/core/tests/test_integration.py
